RUN LIBS.

DECLARE PARAMETER COMMAND.
DECLARE PARAMETER VALUE.
DECLARE PARAMETER APSIS.

SAS ON.

IF COMMAND = "touchdown"
{
	TOUCHDOWN().
} ELSE IF COMMAND = "set" {
	IF APSIS = "periapsis" {
			ALTER_PERIAPSIS_TO(VALUE).
	}

	IF APSIS = "apoapsis" {
			ALTER_APOAPSIS_TO(VALUE).
	}
}

SAS OFF.